title: "St. Marina Coding Class"
description: "Programming & Computer Architecture lessons"

# theme
remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge
